env:
  global:
  # Docker Repository
  - REPO=jgraph/drawio
  # Compute docker tag
  - TAG=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest"; else echo $TRAVIS_BRANCH ; fi`
  - ALPINE_TAG=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo "alpine"; else echo $TRAVIS_BRANCH-alpine ; fi`
  - VERSION=11.3.1
  
sudo: required
services:
  - docker


before_install:
  - docker build -f debian/Dockerfile -t $REPO:$VERSION debian/
  - docker build -f alpine/Dockerfile -t $REPO:$VERSION-alpine alpine/
  - docker run --name 'drawio' -d -p 32733:8080 -p 32734:8443 $REPO:$VERSION
  - docker run --name 'drawio-alpine' -d -p 32735:8080 -p 32736:8443 $REPO:$VERSION-alpine
  - docker ps -a


script:
  # Wait for draw.io to start
  - sleep 10
  - docker logs drawio
  # -i, --include – include protocol headers in the output (H/F)
  # -X, --request – specify request  COMMAND (GET, PUT, DELETE…)  to use
  - docker exec drawio /bin/bash -c "curl -i http://localhost:8080"
  - docker logs drawio-alpine
  - docker exec drawio-alpine /bin/bash -c "curl -i http://localhost:8080"


after_success:
  - echo "$DOCKER_PASS" | docker login -u "$DOCKER_USER" --password-stdin
  - docker tag $REPO:$VERSION $REPO:$TAG
  - docker tag $REPO:$VERSION-alpine $REPO:$ALPINE_TAG
  #- docker tag $REPO:$VERSION $REPO:travis-$TRAVIS_BUILD_NUMBER
  #- docker tag $REPO:$VERSION-alpine $REPO:travis-$TRAVIS_BUILD_NUMBER-alpine
  - docker push $REPO