name: Alpine Docker Image CI

on:
  push:
    branches:
      - master
    tags:
      - 'v*'
    schedule:
      - cron: "05 04 * * 1"

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      REPO: jgraph/drawio
      HTTP_PORT: 32733
      HTTPS_PORT: 32734
      DOCKER_USER: ${{ secrets.DOCKER_USER }}
      DOCKER_PASS: ${{ secrets.DOCKER_PASS }}
    steps:
    - uses: actions/checkout@v2
    - name: Build alpine Docker image
      run: |
        # Get draw.io current latest version
        wget https://raw.githubusercontent.com/jgraph/drawio/master/VERSION
        export VERSION=`cat VERSION`
        docker build -f alpine/Dockerfile -t ${REPO}:${VERSION}-alpine alpine/
        docker run --name "drawio-alpine" -d -p ${HTTP_PORT}:8080 -p ${HTTPS_PORT}:8443 ${REPO}:${VERSION}-alpine
        sleep 10
        docker logs drawio-alpine
        docker exec drawio-alpine /bin/bash -c "curl -i http://localhost:8080"
        export GIT_BRANCH=`echo $GITHUB_REF | awk 'BEGIN { FS = "/" } ; { print $3 }'`
        export TAG=`if [ "$GIT_BRANCH" == "v${VERSION}" ] || [ "$GIT_BRANCH" == "master" ]; then echo "alpine"; else echo $GIT_BRANCH ; fi`
        echo "${DOCKER_PASS}" | docker login -u "${DOCKER_USER}" --password-stdin;
        docker tag ${REPO}:${VERSION}-alpine ${REPO}:$TAG;
        docker push ${REPO}:${TAG};
        docker push ${REPO}:${VERSION}-alpine;
